export const TOGGLELEFT = 'toggleleft'
export const TOGGLERIGHT = 'toggleright'
export const LOADING = 'loading'
export const LOADINGOPEN = 'loadingopen'
export const LOADINGCLOSE = 'loadingclose'
export const MODALOPEN = 'modalopen'
export const MODALCLOSE = 'modalclose'